새로푼 문제 3개
syg0629/algorithm pull request #10
Opened 2023-10-28 15:37 UTC by syg0629

2023.10.28
@f-lab-jake 멘토님
새로푼 문제 3개 PR올립니다.

2023-10-29 04:28 UTC, f-lab-jake requested changes

2023-10-29 04:28 UTC, f-lab-jake commented on programmers/lv.1/231028-완주하지못한선수.ts
> +    }
```
partList[x] ?? = 0;
partList[x]++;
```
로 할수있습니다. 이게 어떤점에서 나을까요?

2023-10-29 04:28 UTC, f-lab-jake commented on programmers/lv.1/231028-폰켓몬.ts
> +  const Dedup: Set<number> = new Set(nums);
왜 변수명에 capital case를 사용했나요?

2023-10-29 04:28 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +function solution(phone_book: string[]) {
잘풀었습니다. `phone_book.sort();` 이걸 뺀 풀이도 한번 생각해볼까요? `phone_book.sort();` 이걸쓴게 나쁜건 아닙니다.

2023-10-29 23:16 UTC, syg0629 commented on programmers/lv.1/231028-완주하지못한선수.ts
> +    }
기존 코드는 `undefined`일 때 `1` 로 초기화 아니면 `+=1`로 되어 있고, 
수정된 코드는 `undefined`일 때 `0`으로 초기화 후 `undefined`가 아닐 때와 동일하게 `++`를 해주고 있어 기존 코드에 비해 일관성이 있습니다.
또 `??`연산자는 `null`과 `undefined`에 대해서만 조건을 걸고 있지만 if문은 여러 조건이 가능하기에 `??`를 쓰는 것이 오류 발생 위험이 적습니다.

2023-10-29 23:20 UTC, syg0629 commented on programmers/lv.1/231028-폰켓몬.ts
> +  const Dedup: Set<number> = new Set(nums);
원래 지었던 변수에 앞부분을 지우고 사용하다가 다른 변수들도 그 형식대로 맞췄나 봅니다... 아이고🤦‍♂️

2023-10-30 01:50 UTC, f-lab-jake commented on programmers/lv.1/231028-완주하지못한선수.ts
> +    partList[x]++;
이 방식에 어떤 장점이 있는지 아시겠나요?

2023-10-30 02:00 UTC, syg0629 commented on programmers/lv.1/231028-완주하지못한선수.ts
> +    partList[x]++;
엇.. 위에 답변 달았는데 
https://github.com/syg0629/algorithm/pull/10#discussion_r1375533249
이 질문이 위 질문과 다른 건가요?

2023-10-30 05:51 UTC, f-lab-jake commented on programmers/lv.1/231028-완주하지못한선수.ts
> +    partList[x]++;
앗 놓쳤습니다. 죄송합니다.

2023-10-30 05:52 UTC, f-lab-jake commented on programmers/lv.1/231028-완주하지못한선수.ts
> +    }
네네 좀더 부연설명을 하자면, `+= 1`의 1과 `= 1`의 1이 서로 커플링이 되어있습니다. 만약에 하나를 바꿔야하면 다른한쪽도 바뀌어야하지요. 고친 코드는 그 커플링을 없앤거지요.
파이썬에는 https://wikidocs.net/33177 요런 기능이 있습니다.

2023-10-30 15:04 UTC, syg0629 commented on programmers/lv.1/231028-완주하지못한선수.ts
> +    }
단어로 커플링이라고 하는군요...  감사합니다 :)

2023-10-31 15:18 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +function solution(phone_book: string[]) {
sort를 뺀 풀이가 잘 생각이 안난다면, 애초에 왜 sort를 했는지를 먼저 설명해봅시다.

2023-10-31 22:33 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +function solution(phone_book: string[]) {
전화번호의 접두사가 필요해서 파라미터 배열에서 오는 값을 정렬하여 사용했습니다. 
`startsWith` 메서드를 발견하여 수정하였습니다 :)!!

2023-11-01 00:09 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +    for (const y of phone_book) {
왜 풀이를 아예 바꿨나요? 이렇게하면 시간초과가 날겁니다.
원래 로직을 유지하면서 sort만 하지 말아보세요.

2023-11-01 00:10 UTC, f-lab-jake requested changes

2023-11-01 00:10 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +    for (const y of phone_book) {
왜 풀이를 아예 바꿨나요? 이렇게하면 시간초과가 날겁니다.
원래 로직을 유지하면서 sort만 하지 말아보세요.

2023-11-01 04:10 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +    for (const y of phone_book) {
sort를 삽입정렬로 바꿨는데 바꾼 코드 또한 시간복잡도가 좋지 않아서 어떻게 해야할지 고민이네요..😥

2023-11-01 09:50 UTC, f-lab-jake requested changes

2023-11-01 09:50 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +function solution(phone_book: string[]) {
지금도 정렬을 했지요. `sort` 메서드를 쓰지말란게 아니고, 정렬을 하지 말란 얘기입니다

2023-11-01 23:34 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +function solution(phone_book: string[]) {
넵! 이제 이해했네요 ㅠㅠ 정렬을 뺀 풀이로 수정하였습니다.

2023-11-02 01:58 UTC, f-lab-jake requested changes

2023-11-02 01:58 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
동작은 할 것입니다.
그런데 애초에 왜 정렬을 했는지를 먼저 설명해볼까요?

2023-11-02 04:11 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
입출력 예제로 `["119", "1192456"]`, `["1192456", "119"]`  경우 둘 다 접두사로 `119`를 가지고 있어 답이 `false`로 나와야 합니다. 하지만 `for`문에서 배열 원소의 길이 만큼 반복을 돌리고 `slice`로 원소를 자르다보니 `["119", "1192456"]`는 `119`가 접두사로 `false`값이 잘 나오지만 `["1192456", "119"]`와 같이 길이가 짧은 원소가 뒤에 있을 경우 `1192456`의 접두사로 판단되지 않기 때문에 `true`가 나오게 됩니다. 하여 길이가 짧은 원소가 접두사가 되어 그 기준으로 판단이 되게끔 정렬을 사용하였습니다.

2023-11-04 11:07 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
멘토링 중에 나왔던 `sort()`메서드와 `if(phoneNum[cutPhoneNum])`의 연관성에 대해 다시 정리하여 말씀드립니다.
 `sort()`메서드는 `phone_book` 배열을 사전 정렬 순서로 바꾸어 주고 그 정렬 기준으로 접두사를 확인하기 위해 사용합니다.  
`cutPhoneNum`은 `phone_book` 배열 원소를 잘라서 `if (phoneNum[cutPhoneNum])`으로 해당 접두사가 이전에 나온 접두사인지 확인하기 위해 사용합니다. 

배열 원소들이 정렬 되어 있고 그 정렬된 기준으로 이전에 나온 접두사인지 확인하기에 `sort()`메서드와 `if(phoneNum[cutPhoneNum])`는 연관성이 있습니다.

이걸 왜 오래 생각하고 있을까 생각해봤는데 멘토님 말씀대로 알고는 있는데 말로 표현하자니 어려웠던 것 같습니다😥

2023-11-04 12:20 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
넵 잘 설명했습니다. 

하지만 여전히 핵심적인 내용은 빠져있습니다. '해당 접두사가 이전에 나온 접두사인지 확인' <- 왜 이렇게해야하나요?
'해당 접두사가 이전에 나온 접두사인지 확인' 이 설명은 문제와 연관지어서 코드를 설명하는게 아닙니다. 코드 내에 스스로 만들어낸 맥락에 대해 설명하는거지요.

2023-11-04 12:21 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
제가 원하는 방식의 설명은 예컨데 이런식이어야 합니다.

'왜 풀이에 이 코드가 포함되어 있나요?' 라고 질문하면
원래 문제 설명에 어떤 문장에 밑줄을 그으며 '이 조건 때문에 그렇습니다'라고 대답해야합니다.

2023-11-04 12:43 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
그러네요.. `if(phoneNum[cutPhoneNum])`으로 해당 접두사가 `phoneNum`에 있는 접두사인지 확인 입니다!!

2023-11-04 13:19 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
문제 설명에 '전화번호부에 적힌 전화번호 중, 한 번호가 다른 번호의 접두어인 경우가 있는지 확인' 이라는 조건이 있습니다. 한 번호는 다른 번호에 비해 길이가 짧아 접두어이기에 주어진 전화번호들을 `sort()`메서드로 정렬 시킨 후 정렬된 기준으로 `phoneNum`에  넣었습니다. `cutPhoneNum`은 `phone_book` 배열 원소를 잘라서 `if(phoneNum[cutPhoneNum])`를 통해 `cutPhoneNum`가 `phoneNum`에 있는 접두어인지 확인하기 위해 사용하였습니다.

2023-11-04 15:32 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
그러니까 `if(phoneNum[cutPhoneNum])` 요부분이 접두어인지 확인하는 거잖아요? 이건 잘했습니다.
그런데 `sort()`는 문제의 조건에서 바로 나오는게 아니라 `if(phoneNum[cutPhoneNum])` 이 코드를 맞게 동작하게하기위해 도입된것입니다. 이해가가나요?
그렇다면 `sort()`를 쓰지않고도 문제를 풀려면 `if(phoneNum[cutPhoneNum])` 이게 `sort()` 없이도 동작하게 해야겠죠. 자 반대로, `sort()`를 빼면 왜 `if(phoneNum[cutPhoneNum])` 이게 의도대로 동작하지 않나요?

2023-11-05 01:11 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
`sort()`는 접두어를 확인하는 기준을 위해 사용하기에 sort를 빼면 기준이 달라져서 `if(phoneNum[cutPhoneNum])`가 의도대로 동작하지 않습니다. 예를 들어 sort를 빼면 `["119", "1192456"]` 배열은 `119`가 기준, `["1192456", "119"]`면 `1192456`가 기준으로 `if(phoneNum[cutPhoneNum])`에서 접두어를 확인하게 됩니다.

2023-11-05 03:37 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
'접두어를 확인하는 기준을 위해 사용하기에' <- 이런게 별로 좋지 못한 설명입니다. '기준'이 뭔가요? 하면 그때부터 또 수렁에 빠집니다. 여기서 '기준'은 설명을 얼렁뚱땅 넘어가려고 쓴 단어입니다.
뒤에 따라오는 구체적인 예시는 정확한데 그걸 제대로 서술하지 못합니다.
x가 y의 접두어일때 x가 y보다 배열에서 뒤에있으면 `phoneNum[cutPhoneNum]`가 `false`가 되어 접두거아 깄는지 여부를 제대로 설명하지 못합니다.
라고 해야합니다.

2023-11-05 04:49 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
넵 알겠습니다. 알려주셔서 감사합니다!!

2023-11-05 06:52 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
그러면 이제 다시 `sort`를 빼고 해봅시다. 힌트를 주자면 `phoneNum`을 먼저 완성하면 됩니다.

2023-11-05 11:05 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +  if (nonDuplicatedPrefix(phone_book)) {
멘토님~ 수정하였습니다 :)

2023-11-05 11:46 UTC, f-lab-jake requested changes

2023-11-05 11:46 UTC, f-lab-jake commented on programmers/lv.2/231028-전화번호목록.ts
> +      if (phoneNum[cutPhoneNum]) return false;
잘했습니다. 처음에 `sort`를 빼보라고한게 이 풀이를 의도하기 위함이었습니다.
이 풀이가 어떤 장점이 있을까요?

2023-11-05 11:48 UTC, f-lab-jake approved these changes

2023-11-05 12:47 UTC, syg0629 commented on programmers/lv.2/231028-전화번호목록.ts
> +      if (phoneNum[cutPhoneNum]) return false;
`phoneNum`에 이미 값이 다 들어갔기 때문에 `if(phoneNum[cutPhoneNum])`에서 접두어를 확인할 때 이전 코드에 비해 예측하기가 더 쉬워졌습니다.

2023-11-05 12:52 UTC, merged