새로푼 문제 4개(23.11.07)
syg0629/algorithm pull request #13
Opened 2023-11-07 07:43 UTC by syg0629

2023.11.07
@f-lab-jake 멘토님
새로푼 문제 4개 PR 올립니다.

2023-11-07 13:48 UTC, f-lab-jake requested changes

2023-11-07 13:48 UTC, f-lab-jake commented on programmers/lv.1/231106-모의고사.ts
> +  const student3: number[] = [3, 3, 1, 1, 2, 2, 4, 4, 5, 5];
규칙이 추가되서 student4, student5, student6까지 다 필요하면 어떻게 해야할까요?
이때 규칙을 배열로 추가하는 것만으로 프로그램이 돌아가게끔 고쳐봅시다.

2023-11-07 13:48 UTC, f-lab-jake commented on programmers/lv.1/231107-기사단원의무기.ts
> +    for (let j = 1; j <= Math.sqrt(i); j++) {
이부분이 뭐하는 코드인가요?

2023-11-07 13:48 UTC, f-lab-jake commented on programmers/lv.2/231107-연속부분수열합의개수.ts
> +  const circularSeq: number[] = [...elements, ...elements];
사실 꼼수치곤 재치있습니다. 시간없을땐 이래도 됩니다. 그런데 꼼수란건 알고있겠죠?
배열을 2배로 늘리지 말고 해봅시다.

2023-11-08 14:42 UTC, syg0629 commented on programmers/lv.1/231106-모의고사.ts
> +  const student3: number[] = [3, 3, 1, 1, 2, 2, 4, 4, 5, 5];
넵 수정하였습니다.

2023-11-08 14:50 UTC, syg0629 commented on programmers/lv.1/231107-기사단원의무기.ts
> +    for (let j = 1; j <= Math.sqrt(i); j++) {
위 코드인 `Math.sqrt()` 작성하기 전에는 `for (let j = 1; j <=i; j++)` 로 작성했었는데 시간 초과가 되었습니다.
그래서 약수는 보통 짝이 있어 2개이고, 그 사이 제곱근은 1개 임을 이용해서 범위를 좁혀 for문이 돌게 하였습니다.

2023-11-09 01:43 UTC, syg0629 commented on programmers/lv.2/231107-연속부분수열합의개수.ts
> +  const circularSeq: number[] = [...elements, ...elements];
넵! 늘리지 않은 풀이로 수정하였습니다!

2023-11-09 04:05 UTC, f-lab-jake requested changes

2023-11-09 04:05 UTC, f-lab-jake commented on programmers/lv.1/231106-모의고사.ts
> +  const studentsAns: number[][] = [
아주 잘했습니다.
사실 따 짜고 이렇게 고치는게 아니고 첨부터 이렇게 짜는게 더 빠르게되는것이 충분히 가능합니다.

2023-11-09 04:05 UTC, f-lab-jake commented on programmers/lv.1/231107-기사단원의무기.ts
> +    for (let j = 1; j <= Math.sqrt(i); j++) {
> 그래서 약수는 보통 짝이 있어 2개이고, 그 사이 제곱근은 1개 임을 이용해서 범위를 좁혀 for문이 돌게 하였습니다.
요거 설명을 개선해보세요.

그리고 사실 이걸 물은건 아닙니다. 저부분이 소수를 구하는 부분이잖아요? 적절히 함수로 분리해봅시다.

2023-11-09 04:05 UTC, f-lab-jake commented on programmers/lv.2/231107-연속부분수열합의개수.ts
> +  const set: Set<number> = new Set();
`sums` 정도가 좋습니다. 왜그럴까요?

2023-11-09 04:05 UTC, f-lab-jake commented on programmers/lv.2/231107-연속부분수열합의개수.ts
> +  const eleLen: number = elements.length;
이런건 굳이 변수로 안빼도 됩니다.

2023-11-09 12:38 UTC, syg0629 commented on programmers/lv.2/231107-연속부분수열합의개수.ts
> +  const set: Set<number> = new Set();
더해진 값들의 집합이니 멘토님 말씀대로 `sums`가 좋겠네요!

2023-11-09 12:38 UTC, syg0629 commented on programmers/lv.2/231107-연속부분수열합의개수.ts
> +  const eleLen: number = elements.length;
넵 알겠습니다 :)

2023-11-09 13:20 UTC, syg0629 commented on programmers/lv.1/231107-기사단원의무기.ts
> +    for (let j = 1; j <= Math.sqrt(i); j++) {
넵 분리하였습니다 !

2023-11-09 23:56 UTC, f-lab-jake approved these changes

2023-11-09 23:57 UTC, f-lab-jake requested changes

2023-11-09 23:57 UTC, f-lab-jake commented on programmers/lv.1/231107-기사단원의무기.ts
> +      if (i / j === j) divisorCnt++;
여기 이 코드가 있는게 좋지 않습니다

2023-11-12 10:44 UTC, merged