새로푼 문제 3개(23.11.10)
syg0629/algorithm pull request #14
Opened 2023-11-12 10:50 UTC by syg0629

2023.11.10
@f-lab-jake 멘토님
새로푼 문제 3개 PR 올립니다 :)

2023-11-12 14:09 UTC, f-lab-jake requested changes

2023-11-12 14:09 UTC, f-lab-jake commented on programmers/lv.1/231110-소수만들기.ts
> +  }
잘 풀었습니다.
그런데 이 풀이의 어떤 부분이 불만족스러워야할까요?

2023-11-12 14:09 UTC, f-lab-jake commented on programmers/lv.2/231110-할인행사.ts
> +      }
control flow에 대한 구문을 더 위로 올려봅시다.

2023-11-18 05:37 UTC, syg0629 commented on programmers/lv.1/231110-소수만들기.ts
> +  }
`nums.length` 뒤의 숫자는 없어도 되는데 붙였고, 
전체적인 풀이가 다 연결되어 있지만, 실제 코드는 연결 되어 있지 않아 유지보수를 하게 된다면 `let j = i + 1`나 `let e = j + 1;` 숫자들을 하나씩 다 바꾸어줘야하는 번거로움이 있습니다.

2023-11-18 06:11 UTC, f-lab-jake commented on programmers/lv.1/231110-소수만들기.ts
> +  }
맞습니다. 코드가 어떤 방향으로 확장불가능할까요?

2023-11-18 07:00 UTC, syg0629 commented on programmers/lv.1/231110-소수만들기.ts
> +  }
`let j = i + 1` 이런 식으로 1이 하드코딩이 되어 있기에 재사용성이 좋지 못해 확장 불가능합니다.

2023-11-18 09:59 UTC, syg0629 commented on programmers/lv.2/231110-할인행사.ts
> +      }
음.. 제가 멘토님 의도를 정확히 파악 못하고 있는 듯 한데 ㅠㅠ위에 집어주신 break문을 위로 올리라는 의미가 맞으실까요?

2023-11-18 18:17 UTC, f-lab-jake commented on programmers/lv.1/231110-소수만들기.ts
> +  }
틀리지도 맞지도 않는 대답입니다. 이건 제 질문에 대한 대답이 아니지요. 왜그럴까요?

2023-11-21 10:28 UTC, syg0629 commented on programmers/lv.1/231110-소수만들기.ts
> +  }
`N개의 수를 더할 경우`로 문제의 조건을 바꾼 풀이 올렸습니다 :)

2023-11-23 14:53 UTC, f-lab-jake requested changes
잘했습니다.
그런데 맞는 코드란걸 파악하기가 쉽지않죠? 다음 멘토링전까지 개선할수있는데까지 개선해봅시다.

2024-01-04 13:58 UTC, f-lab-jake requested changes

2024-09-19 14:34 UTC, merged