새로푼 문제 2개(23.11.27)
syg0629/algorithm pull request #15
Opened 2023-11-27 02:32 UTC by syg0629

2023.11.27
@f-lab-jake 멘토님
새로푼 문제 2개 PR 올립니다 :)

2023-11-27 04:24 UTC, f-lab-jake requested changes

2023-11-27 04:24 UTC, f-lab-jake commented on programmers/lv.2/231126-타겟넘버.ts
> +  findTargetCnt(0, 0);
잘햇습니다. 그런데 방법을좀 바꿔봅시다. `answer`와 같은 재귀함수 밖의 변수를 변경하지 말고 해봅시다. 대신 리턴 값을 사용합니다.

결국 답은 `return findTargetCnt(0,0)` 같은 형식이 되어야합니다

2023-11-27 04:24 UTC, f-lab-jake commented on programmers/lv.2/231127-소수찾기.ts
> +function solution(numbers: string): number {
이 문제도 타겟넘버에서 말한 방식으로 고쳐봅시다. 시간초과가 날수있는데 일단 괜찮습니다.

2023-11-28 08:37 UTC, syg0629 commented on programmers/lv.2/231126-타겟넘버.ts
> +  findTargetCnt(0, 0);
넵 수정하였습니다.

2023-11-28 08:37 UTC, syg0629 commented on programmers/lv.2/231127-소수찾기.ts
> +function solution(numbers: string): number {
넵 이것도 수정하였습니다!

2023-11-28 10:30 UTC, bglgwyng requested changes

2023-11-28 10:30 UTC, bglgwyng commented on programmers/lv.2/231126-타겟넘버.ts
> +  return findTargetCnt(0, 0);
여기서 `findTargetCnt(numbers, target)` 이렇게 호출하도록 수정해봅시다.
그러면 `findTargetCnt`는 함수 밖의 변수를 참조할 필요가 없게 됩니다.

2023-11-28 10:30 UTC, bglgwyng commented on programmers/lv.2/231127-소수찾기.ts
> +  ): number {
`number[]`를 리턴하도록 하고 거기서부터 set을 만듭시다. 시간초과가 날수있찌만 괜찮습니다.

2023-11-29 05:52 UTC, syg0629 commented on programmers/lv.2/231127-소수찾기.ts
> +  ): number {
`number[]`로 리턴하도록해서 수정하였습니다.

2023-11-29 06:04 UTC, syg0629 commented on programmers/lv.2/231126-타겟넘버.ts
> +  return findTargetCnt(0, 0);
이거 계속 해보고 있는데 잘 모르겠습니다. 
기존에는 `findTargetCnt(idx + 1, sum + numbers[idx])` 아니면 `findTargetCnt(idx + 1, sum - numbers[idx]);`를 해서 재귀함수를 사용했는데 `findTargetCnt(numbers, target);`로 하게 되면 재귀가 안되지 않나요..? 뭔가 감을 못잡고 있는 듯 합니다 ㅠㅠ

2023-11-29 06:29 UTC, f-lab-jake requested changes

2023-11-29 06:29 UTC, f-lab-jake commented on programmers/lv.2/231127-소수찾기.ts
> +  findNum(splittedNum, "");
리턴값을 안쓸거면 왜 리턴을 하죠?

2023-11-29 07:05 UTC, syg0629 commented on programmers/lv.2/231127-소수찾기.ts
> +  findNum(splittedNum, "");
그러네요. 다시 수정하였습니다 :)

2023-11-29 07:33 UTC, f-lab-jake commented on programmers/lv.2/231126-타겟넘버.ts
> +  return findTargetCnt(0, 0);
저렇게 호출해도되도록 타입과 내부 구현도 함께 바꾸면 됩니다.

2023-11-29 07:56 UTC, f-lab-jake requested changes

2023-11-29 07:56 UTC, f-lab-jake commented on programmers/lv.2/231127-소수찾기.ts
> +        findNum(copySplittedNum, newNum, primeNewNum);
여기서도 리턴값을 활용하세요.

2023-11-29 08:45 UTC, syg0629 commented on programmers/lv.2/231127-소수찾기.ts
> +        findNum(copySplittedNum, newNum, primeNewNum);
넵 활용하도록 수정하였습니다!

2024-01-04 02:25 UTC, bglgwyng requested changes

2024-01-04 02:25 UTC, bglgwyng commented on programmers/lv.2/231127-소수찾기.ts
>      if (splittedNum.length >= 1) {
없어도됩니다.

2024-01-04 02:25 UTC, bglgwyng commented on programmers/lv.2/231127-소수찾기.ts
>            primeNewNum.push(numberNewNum);
`primeNewNum`을 변경하지 말고 풀어보세요.

2024-01-04 02:25 UTC, bglgwyng commented on programmers/lv.2/231127-소수찾기.ts
>          const copySplittedNum: string[] = [...splittedNum];
전반적으로 변수명이

2024-01-04 02:26 UTC, bglgwyng commented
전반적으로 변수명이 이상합니다. 일단 배열이면 뒤에 `s`를 붙이세요. 그리고 `primeNewNum`은 그냥 `newPrime`이면 됩니다.
또 `splittedNum`은 아주 안좋습니다. 변수명이 변수의 값에 대해 아무것도 설명하지 않는데요. 왜그럴까요?

2024-01-05 00:44 UTC, syg0629 commented on programmers/lv.2/231127-소수찾기.ts
>      if (splittedNum.length >= 1) {
네 수정하였습니다.

2024-01-05 00:47 UTC, syg0629 commented on programmers/lv.2/231127-소수찾기.ts
>            primeNewNum.push(numberNewNum);
`primeNewNum` 배열을 만들어 set에 넣었는데 처음부터 set으로 넣게 수정하였습니다.

2024-01-05 00:59 UTC, syg0629 commented on programmers/lv.2/231127-소수찾기.ts
>          const copySplittedNum: string[] = [...splittedNum];
넵 변수명 수정하였습니다 :)

2024-01-05 01:46 UTC, f-lab-jake requested changes

2024-01-05 01:46 UTC, f-lab-jake commented on programmers/lv.2/231127-소수찾기.ts
> +  findNum(numberChars, "", set);
지금 고치라는 방향성 자체를 잘못 이해하고 계십니다.
`findNum`이 외부 변수를 변경하지 않고 값을 리턴하느것만으로 역할을 다하도록 고치란 얘깁니다.
`primeNewNum`을 변경하는 대신 다른걸 변경하는데 아니라요.

2024-01-05 01:46 UTC, f-lab-jake commented on programmers/lv.2/231127-소수찾기.ts
> +  findNum(numberChars, "", set);
지금처럼 고칠땐 왜 이렇게 고쳐야하는지도 잘 납득이 안갈것 같습니다. 그럴땐 다시 질문을 주세요.

2024-01-07 08:35 UTC, syg0629 commented on programmers/lv.2/231127-소수찾기.ts
> +  findNum(numberChars, "", set);
외부변수를 쓰면 코드의 동작 이해 및 예측이 어려워지기에 사용하지 않는 것이 좋다고 말씀해 주셨습니다만, 소수인 것을 찾아서 배열에 저장해야 하기에 변경이 있어야 하지 않나요..? 꼭 배열을 쓰지 않더라도 소수를 발견하면 변경은 해야하지 않나 싶어서요..

2024-01-07 10:44 UTC, f-lab-jake commented on programmers/lv.2/231127-소수찾기.ts
> +  findNum(numberChars, "", set);
변경대신에 return값을 쓰면됩니다.

2024-01-08 22:26 UTC, syg0629 commented on programmers/lv.2/231127-소수찾기.ts
> +  findNum(numberChars, "", set);
수정하였습니다 :)!!

2024-01-11 10:17 UTC, f-lab-jake requested changes

2024-01-11 10:17 UTC, f-lab-jake commented on programmers/lv.2/231127-소수찾기.ts
> +        : findNum(numExceptI, newNum);
return을 한번만 쓰라는건 힌트입니다. 결국 더 나은 코드를 짜란 얘기죠.
쉽게 캐치할수있는 개선 포인트도 놓쳤습니다.

2024-09-19 14:34 UTC, merged