새로운 문제 2개(24.01.12)
syg0629/algorithm pull request #17
Opened 2024-01-12 07:22 UTC by syg0629

2024.01.12
@f-lab-jake 멘토님
새로푼 문제 2개 PR 올립니다 :)

2024-01-14 04:51 UTC, f-lab-jake requested changes

2024-01-14 04:51 UTC, f-lab-jake commented on programmers/lv.2/240111-튜플.ts
> +}
변수명을 동사로 하지 마세요. 그리고 배열이나 set등의 컬렉션이면 복수형을 쓰세요.

2024-01-14 04:51 UTC, f-lab-jake commented on programmers/lv.2/240112-[1차]캐시.ts
> +        cache.delete(cache.keys().next().value);
이게 `LRU` 방식이 맞나요?

2024-01-16 22:43 UTC, syg0629 commented on programmers/lv.2/240112-[1차]캐시.ts
> +        cache.delete(cache.keys().next().value);
`LRU`가 가장 오랫동안 참조되지 않은 페이지를 교체하는 방식이니 
이미 캐시에 존재하는 도시가 참조되면 삭제 후 다시 추가로 교체를 한 것이니 `LRU` 방식이지 않나요?

2024-01-16 22:44 UTC, syg0629 commented on programmers/lv.2/240111-튜플.ts
> +}
넵 알겠습니다!

2024-01-17 02:08 UTC, f-lab-jake commented on programmers/lv.2/240112-[1차]캐시.ts
> +        cache.delete(cache.keys().next().value);
가장 오랫동안 참조되지 않은 페이지가 맞나요?

2024-09-19 14:35 UTC, merged