새로푼 문제
syg0629/algorithm pull request #21
Opened 2024-01-25 14:59 UTC by syg0629

맨토님
새로푼 문제 올립니다!

2024-01-26 07:11 UTC, f-lab-jake requested changes

2024-01-26 07:11 UTC, f-lab-jake commented on programmers/lv.0/240125-문자열안에문자열.ts
> +  const isStr2InStr1 = str1.split(str2);
용도에 맞는 함수를 활용하세요

2024-01-26 07:11 UTC, f-lab-jake commented on programmers/lv.0/240125-배열의평균값.ts
> +  return numbers.reduce((x: number, y: number) => x + y, 0) / numbers.length;
lodash의 `sum`을 쓰세요

2024-01-26 07:11 UTC, f-lab-jake commented on programmers/lv.0/240125-짝수의합.ts
> +  }
두배 효율적으로 짤수있습니다

2024-01-26 07:11 UTC, f-lab-jake commented on programmers/lv.0/240125-첫번째로나오는음수.ts
> +}
요건 잘했습니다

2024-01-26 07:11 UTC, f-lab-jake commented on programmers/lv.0/240126-배열두배만들기.ts
> +  let doubling = numbers.map((x: number) => x * 2);
왜 let이죠? 같은 실수를 반복하지 맙시다.

2024-01-26 07:11 UTC, f-lab-jake commented on programmers/lv.0/240126-양꼬치.ts
> +}
더 간결하게 할수있습니다.

2024-01-26 07:11 UTC, f-lab-jake commented on programmers/lv.0/240126-중앙값구하기.ts
> +function solution(array: number[]): number | undefined {
어떤경우에 `undefined`가 리턴되죠?

2024-01-26 13:30 UTC, syg0629 commented on programmers/lv.0/240125-짝수의합.ts
> +  }
넵 수정하였습니다.

2024-01-26 13:31 UTC, syg0629 commented on programmers/lv.0/240126-배열두배만들기.ts
> +  let doubling = numbers.map((x: number) => x * 2);
넵 ㅠㅠ 수정하였습니다.

2024-01-26 13:31 UTC, syg0629 commented on programmers/lv.0/240126-양꼬치.ts
> +}
넵~ 더 간결하게 수정하였습니다.

2024-01-26 13:34 UTC, syg0629 commented on programmers/lv.0/240126-중앙값구하기.ts
> +function solution(array: number[]): number | undefined {
매개변수 `array`가 빈 배열이 주어지게 되면 `undefined`가 리턴됩니다. 
프로그래머스 문제 제한조건에 `0 < array의 길이 < 100`가 있긴 한데 TS오류로 넣게 되었습니다..

2024-01-26 13:39 UTC, syg0629 commented on programmers/lv.0/240125-배열의평균값.ts
> +  return numbers.reduce((x: number, y: number) => x + y, 0) / numbers.length;
넵 lodash `sum`으로 수정하였습니다~

2024-01-26 13:54 UTC, syg0629 commented on programmers/lv.0/240125-문자열안에문자열.ts
> +  const isStr2InStr1 = str1.split(str2);
넵! 멘토님 말씀대로 `split`은 구분자로 문자열을 나누기 위한 것이라 용도에 맞는 `includes`로 수정하였습니다.

2024-01-28 10:32 UTC, bglgwyng requested changes

2024-01-28 10:32 UTC, bglgwyng commented on programmers/lv.0/240126-중앙값구하기.ts
> +function solution(array: number[]): number | undefined {
그럴땐 !를 쓰세요.

2024-01-28 10:34 UTC, f-lab-jake requested changes

2024-01-28 10:34 UTC, f-lab-jake commented on programmers/lv.0/240126-중앙값구하기.ts
> +function solution(array: number[]): number | undefined {
!를 쓰세요

2024-01-28 10:52 UTC, syg0629 commented on programmers/lv.0/240126-중앙값구하기.ts
> +function solution(array: number[]): number | undefined {
넵 `!`를 썼습니다!

2024-01-28 11:57 UTC, f-lab-jake requested changes

2024-01-28 11:57 UTC, f-lab-jake commented on programmers/lv.0/240126-중앙값구하기.ts
> +    .at(Math.floor(array.length / 2))!;
일반적으로 !를 언제 써도 되는지 설명해볼까요?

2024-01-28 13:16 UTC, syg0629 commented on programmers/lv.0/240126-중앙값구하기.ts
> +    .at(Math.floor(array.length / 2))!;
`null`이나 `undefined`가 아닌 타입이 확실할 때 사용해도 됩니다.

2024-01-28 13:30 UTC, f-lab-jake commented on programmers/lv.0/240126-중앙값구하기.ts
> +    .at(Math.floor(array.length / 2))!;
넵 맞습니다. 그런데 최대한 피해야하기도 합니다. 왜그럴까요?

2024-01-28 13:54 UTC, syg0629 commented on programmers/lv.0/240126-중앙값구하기.ts
> +    .at(Math.floor(array.length / 2))!;
타입을 단언하게 되니 나중에 오류가 발생하게 되더라도 발견하가 쉽지 않고, 크게 보면 타입스크립트를 쓰는 이유가 없어질 것 같습니다.

2024-01-28 16:48 UTC, f-lab-jake commented on programmers/lv.0/240126-중앙값구하기.ts
> +    .at(Math.floor(array.length / 2))!;
넵 맞습니다. 타입스크립트 쓰는 이유가 없어진다는게 정확합니다.
https://www.fronttigger.dev/2022/typescript/type-guard
요방법은 뭐가 나을까요?

2024-01-28 22:40 UTC, syg0629 commented on programmers/lv.0/240126-중앙값구하기.ts
> +    .at(Math.floor(array.length / 2))!;
`assert function`는 타입 단언이 아닌 타입을 보장으로 원하는 반환값을 얻을 수 있으면서 `!`와 달리 어디서 오류가 나는지 찾기가 수월합니다.

2024-01-29 01:28 UTC, f-lab-jake commented on programmers/lv.0/240126-중앙값구하기.ts
> +    .at(Math.floor(array.length / 2))!;
오 정확합니다. 오류가 찾기 쉬운게 첫번째 좋은 점이고요.
하나 더 들어가면 오류가 빨리 발생하는거 자체도 좋습니다. 왜그럴까요?

2024-01-29 04:39 UTC, syg0629 commented on programmers/lv.0/240126-중앙값구하기.ts
> +    .at(Math.floor(array.length / 2))!;
코드는 위에서 부터 순차적으로 진행되기에 오류가 빨리 발생했다는 것은 고쳐야할 범위가 느리가 발생한 것에 비해 적기 때문에 더 좋을 것 같습니다.

2024-01-29 05:28 UTC, f-lab-jake commented on programmers/lv.0/240126-중앙값구하기.ts
> +    .at(Math.floor(array.length / 2))!;
동어반복에 가깝죠? 실제 개발에서 어떤 이득이 있는지까지 이어질수있는 설명이 맞나요?

2024-01-29 22:25 UTC, syg0629 commented on programmers/lv.0/240126-중앙값구하기.ts
> +    .at(Math.floor(array.length / 2))!;
잠재적인 파급효과를 제한할 수 있는지 없는지의 문제로 `assert function`에 있는 코드가 오류가 발생하게 된 경우, 에러 페이지나 오류 메세지는 뜨겠지만 그 함수 밑에 있는 코드는 모두 실행되지 않기에 발생하는 문제가 예상 범위 안이여서 오류가 빨리 발생하는 것이 좋습니다. 코드가 잘못된 동작을 하고 있는데 모르고 있다면 후에는 예상치 못한 문제가 더 크게 발생할 수도 있습니다.  알려주셔서 감사합니다 :)

2024-01-30 14:17 UTC, f-lab-jake approved these changes

2024-01-30 15:25 UTC, merged