새로푼 문제(24.01.27)
syg0629/algorithm pull request #22
Opened 2024-01-27 14:34 UTC by syg0629

2024.01.27
@f-lab-jake 멘토님
새로푼 문제 PR 올립니다 :)

2024-01-27 14:40 UTC, f-lab-jake requested changes

2024-01-27 14:40 UTC, f-lab-jake commented on programmers/lv.0/240127-머쓱이보다키큰사람.ts
> +  return cnt;
`countBy` 써보세요

2024-01-27 14:40 UTC, f-lab-jake commented on programmers/lv.0/240127-점의위치구하기.ts
> +function solution(dot: number[]): number | undefined {
타입 개선합시다. 길이 2개인 배열인건 보장되잖아요.

2024-01-27 14:40 UTC, f-lab-jake commented on programmers/lv.0/240127-점의위치구하기.ts
> +    } else return 4;
반복되는 인덱싱(`dot[0]`같은거)를 피합시다

2024-01-27 14:40 UTC, f-lab-jake commented on programmers/lv.0/240127-피자나눠먹기(2).ts
> +  return pizza / 6;
간결하게 줄여보세요

2024-01-28 08:27 UTC, syg0629 commented on programmers/lv.0/240127-머쓱이보다키큰사람.ts
> +  return cnt;
`countBy`로 수정하였습니다.

2024-01-28 08:27 UTC, syg0629 commented on programmers/lv.0/240127-점의위치구하기.ts
> +function solution(dot: number[]): number | undefined {
넵 수정하였습니다~

2024-01-28 08:28 UTC, syg0629 commented on programmers/lv.0/240127-점의위치구하기.ts
> +    } else return 4;
넵 구조분해할당으로 수정하였습니다

2024-01-28 08:28 UTC, syg0629 commented on programmers/lv.0/240127-피자나눠먹기(2).ts
> +  return pizza / 6;
while문으로 간결하게 수정하였습니다.

2024-01-28 10:33 UTC, f-lab-jake requested changes

2024-01-28 10:33 UTC, f-lab-jake commented on programmers/lv.0/240127-머쓱이보다키큰사람.ts
> +  return test.true || 0;
무슨 의미죠?

2024-01-28 10:33 UTC, f-lab-jake commented on programmers/lv.0/240127-점의위치구하기.ts
> +  } else return 4;
삼항연산자를 써봅시다. 뭐가 더 나을까요?

2024-01-28 10:43 UTC, syg0629 commented on programmers/lv.0/240127-머쓱이보다키큰사람.ts
> +  return test.true || 0;
혹시 변수명 때문이면 잘못 올려서 바로 https://github.com/syg0629/algorithm/pull/22/commits/506087dee47a4773c47907b32c4e528490f8eed6
로 다시 올렸습니다 ㅠㅠ

2024-01-28 10:53 UTC, f-lab-jake commented on programmers/lv.0/240127-머쓱이보다키큰사람.ts
> +  return test.true || 0;
`.true`가 무슨 뜻인가요?

2024-01-28 12:39 UTC, syg0629 commented on programmers/lv.0/240127-점의위치구하기.ts
> +  } else return 4;
기존 if문으로 작성했을 때는 등호가 바뀌거나 변수명이 바뀌는 식으로 비슷한 코드가 반복 되었는데 삼항연산자로 작성하게 되니 반복적이던 코드를 줄일 수 있어서 더 좋네요.

2024-01-28 12:45 UTC, syg0629 commented on programmers/lv.0/240127-머쓱이보다키큰사람.ts
> +  return test.true || 0;
위 코드로 말씀드리면  return test를 출력해보니 `console.log(solution([149, 180, 192, 170], 167)); //3`의 경우
`{ false: 1, true: 3 }` 이런 식으로 호출되기에 test.true값을 가져오게 하였습니다.

2024-01-28 13:29 UTC, f-lab-jake commented on programmers/lv.0/240127-점의위치구하기.ts
> +  } else return 4;
맞습니다. 반복을 줄일수 있는것이 첫번째 장점입니다.
또한 return이 앞으로 오는게 두번째 장점입니다. 왜그럴까요?

2024-01-28 13:46 UTC, syg0629 commented on programmers/lv.0/240127-점의위치구하기.ts
> +  } else return 4;
기존 작성했던 if문의 경우 조건이 연달아 붙어 있어 코드의 흐름이나 내용이 어떻게 바뀌게 될지 끝까지 확인해야 하는데 삼항연산자의 경우 return이 바로 나와 예상이 비교적 쉽습니다.

2024-01-30 12:06 UTC, f-lab-jake requested changes

2024-01-30 12:06 UTC, f-lab-jake commented on programmers/lv.0/240127-점의위치구하기.ts
> +  const [num1, num2] = dot;
이름을 주더라도 아무 의미없는 이름을 주면 읽는데 도움이 안되죠.
좌표니까 `x` `y` 정도가 좋겠네요.

2024-01-30 14:58 UTC, syg0629 commented on programmers/lv.0/240127-점의위치구하기.ts
> +  const [num1, num2] = dot;
와...  `x`, `y` 좋네요!! 수정하였습니다

2024-01-30 15:49 UTC, f-lab-jake commented on programmers/lv.0/240127-머쓱이보다키큰사람.ts
> +  return test.true || 0;
아 제가 `countBy` 동작을 잘못아고 있었네요. 일단 이렇게 하더라도 `??`를 쓰는게 맞습니다.

2024-01-30 17:17 UTC, f-lab-jake approved these changes

2024-01-30 17:18 UTC, f-lab-jake commented on programmers/lv.0/240127-머쓱이보다키큰사람.ts
> +  return test.true || 0;
구체적이라서 쓰는게 무슨 뜻이죠? 두개는 그냥 동작이 다릅니다.

2024-01-30 23:33 UTC, syg0629 commented on programmers/lv.0/240127-머쓱이보다키큰사람.ts
> +  return test.true || 0;
`??`연산자는 `null`, `undefined`만 조건으로 하는데 `||`연산자는 falsy한 값들(0, null, undefined, '')을 다 조건으로 해서 구체적이라고 생각했습니다.  그런데 찾아보니 `undefined || null || 0`는 모두 falsy이므로 마지막 값인 `0`을 반환. 또 `??`연산자는 정의한 값을 반환하지만 `||`는 truthy값을 반환하기에 `let height = 0; console.log(height || 100);`에서 0은 falsy취급. 100을 반환한다는 내용을 보게 되어 `??`을 써야겠다는 생각이 확실히 들게 되었습니다. 알려주셔서 감사합니다 :)

2024-01-30 23:54 UTC, merged