새로운 문제 풀이 9개(24.01.28)
syg0629/algorithm pull request #23
Opened 2024-01-29 13:19 UTC by syg0629

2024.01.28
@f-lab-jake 멘토님
새로푼 문제 풀이 PR 올립니다 :)

2024-01-30 14:18 UTC, f-lab-jake requested changes

2024-01-30 14:18 UTC, f-lab-jake commented on programmers/lv.0/240128-삼각형의완성조건(1).ts
>  function solution(sides: number[]): number {
`[number, number]`가 맞습니다

2024-01-31 00:29 UTC, syg0629 commented on programmers/lv.0/240128-삼각형의완성조건(1).ts
>  function solution(sides: number[]): number {
`sides`의 길이가 3으로 주어지는게 확실하니 매개변수 타입도 딱 지정해놓는군요👀. 수정하였습니다!

2024-01-31 03:15 UTC, f-lab-jake approved these changes

2024-01-31 03:23 UTC, merged