새로푼 문제풀이 10개
syg0629/algorithm pull request #25
Opened 2024-01-30 09:36 UTC by syg0629

2024.01.30
@f-lab-jake 멘토님
새로푼 문제 풀이 PR 올립니다 :)
간결하게 풀도록 하였습니다.

2024-01-30 14:19 UTC, f-lab-jake requested changes

2024-01-30 14:19 UTC, f-lab-jake commented on programmers/lv.0/240130-369게임.ts
> +    .filter((x) => x === 3 || x === 6 || x === 9).length;
개선해봅시다.

2024-01-30 14:19 UTC, f-lab-jake commented on programmers/lv.0/240130-숫자찾기.ts
> +  }
`findIndex`쓰면 되겠죠?

2024-01-30 14:19 UTC, f-lab-jake commented on programmers/lv.0/240130-외계행성의나이.ts
> +  ];
좀 줄여봅시다

2024-01-30 14:19 UTC, f-lab-jake commented on programmers/lv.0/240130-합성수찾기.ts
> +function isNotPrime(num: number): boolean {
`isPrime`으로 바꿔보세요

2024-01-31 00:49 UTC, syg0629 commented on programmers/lv.0/240130-외계행성의나이.ts
> +  ];
넵! 말씀해주신 `ageLetters`을 string[]에서 string로 바꾸고, map순회 시 배열로 순회하게 수정하였습니다.

2024-01-31 01:59 UTC, syg0629 commented on programmers/lv.0/240130-합성수찾기.ts
> +function isNotPrime(num: number): boolean {
넵 수정하였습니다.

2024-01-31 03:15 UTC, f-lab-jake approved these changes

2024-01-31 04:05 UTC, syg0629 commented on programmers/lv.0/240130-숫자찾기.ts
> +  }
넵 `findIndex`로 수정하였습니다.

2024-01-31 04:06 UTC, syg0629 commented on programmers/lv.0/240130-369게임.ts
> +    .filter((x) => x === 3 || x === 6 || x === 9).length;
filter 조건을 3의 배수로 하는 방법을 썼다가 set을 쓰는 방법으로 다시 수정해보았습니다.

2024-01-31 04:52 UTC, f-lab-jake commented on programmers/lv.0/240130-369게임.ts
> +  return [...order.toString()].map(Number).filter((x) => set.has(x)).length;
잘했습니다. 이런 작은건 `[1,2,3].includes(x)` 같은 식으로 해도 됩니다.

2024-02-01 05:16 UTC, merged