새로푼 문제 7개(24.02.03)
syg0629/algorithm pull request #27
Opened 2024-02-03 14:49 UTC by syg0629

2024.02.03
새로푼 문제 풀이 PR 올립니다 :)

2024-02-04 04:12 UTC, f-lab-jake requested changes

2024-02-04 04:12 UTC, f-lab-jake commented on programmers/lv.0/240203-소인수분해.ts
> +  }
잘했습니다

2024-02-04 04:12 UTC, f-lab-jake commented on programmers/lv.0/240203-이진수더하기.ts
> +  return (parseInt(bin1, 2) + parseInt(bin2, 2)).toString(2);
`parseInt` 안쓰고 풀어볼까요?

2024-02-04 04:12 UTC, f-lab-jake commented on programmers/lv.0/240203-컨트롤제트.ts
> +  return numbers.reduce((x, y) => x + y, 0);
코드만 보면 저 문제에 대한 해답인지 이해하기 어렵습니다. 문제의 조건과 코드가 자명하게 이어지도록 짜보세요.

2024-02-04 04:12 UTC, f-lab-jake commented on programmers/lv.0/240203-한번만등장한문자.ts
> +  const letterCnt: Record<string, number> = {};
Map 쓰십쇼

2024-02-04 16:11 UTC, syg0629 commented on programmers/lv.0/240203-한번만등장한문자.ts
> +  const letterCnt: Record<string, number> = {};
넵 수정하였습니다!

2024-02-05 04:44 UTC, syg0629 commented on programmers/lv.0/240203-컨트롤제트.ts
> +  return numbers.reduce((x, y) => x + y, 0);
넵 수정하였습니다!

2024-02-05 10:06 UTC, f-lab-jake approved these changes
아

2024-02-05 10:06 UTC, f-lab-jake commented on programmers/lv.0/240203-컨트롤제트.ts
> +  return stack.map(Number).reduce((x, y) => x + y, 0);
아주 잘했습니다. 각단계가 무얼하는지가 정확하게 드러납니다.

2024-02-13 05:02 UTC, syg0629 commented on programmers/lv.0/240203-이진수더하기.ts
> +  return (parseInt(bin1, 2) + parseInt(bin2, 2)).toString(2);
넵 `parseInt` 안 쓰는 방법으로 수정하였습니다!

2024-02-13 05:07 UTC, f-lab-jake approved these changes

2024-02-13 05:07 UTC, f-lab-jake commented on programmers/lv.0/240203-이진수더하기.ts
> +};
매우 잘했습니다

2024-02-13 05:50 UTC, merged