새로운 문제풀이 10개(24.02.09)
syg0629/algorithm pull request #29
Opened 2024-02-09 12:24 UTC by syg0629

2024.02.09
@f-lab-jake 멘토님
새로푼 문제 풀이 PR 올립니다 :)

2024-02-09 12:45 UTC, f-lab-jake requested changes

2024-02-09 12:45 UTC, f-lab-jake commented on programmers/lv.0/240207-구슬을나누는경우의수.ts
> +  }
`shareF`를 쓰지않고 풀어보세요.

2024-02-09 12:45 UTC, f-lab-jake commented on programmers/lv.0/240207-구슬을나누는경우의수.ts
> +  return Math.floor(ballsF / shareF);
`floor`를 안쓰는게 맞습니다. 소수점이 나올일이 없습니다.

2024-02-09 12:45 UTC, f-lab-jake commented on programmers/lv.0/240208-삼각형의완성조건(2).ts
> +  }
효율적으로 개선해보세요

2024-02-09 12:45 UTC, f-lab-jake commented on programmers/lv.0/240209-캐릭터의좌표.ts
> +    if (range[0] < Math.abs(x)) {
`range[0]` 같은거 미리 destructuring 해놓으세요.
무슨의미인지 알기 힘듭니다.

2024-02-11 14:32 UTC, syg0629 commented on programmers/lv.0/240207-구슬을나누는경우의수.ts
> +  return Math.floor(ballsF / shareF);
넵 수정하였습니다!

2024-02-11 14:32 UTC, syg0629 commented on programmers/lv.0/240207-구슬을나누는경우의수.ts
> +  }
`shareF`를 안쓰고 풀었는데 혹시 생각하시던 방법이 맞을까요?

2024-02-11 14:37 UTC, syg0629 commented on programmers/lv.0/240208-삼각형의완성조건(2).ts
> +  }
넵 수정하였습니다~

2024-02-11 14:37 UTC, syg0629 commented on programmers/lv.0/240209-캐릭터의좌표.ts
> +    if (range[0] < Math.abs(x)) {
구조 분해 할당 사용하였습니다.

2024-02-12 13:19 UTC, f-lab-jake requested changes

2024-02-12 13:19 UTC, f-lab-jake commented on programmers/lv.0/240208-삼각형의완성조건(2).ts
>    }
이 코드가 뭘 하고 있는지 의미를 생각해보세요

2024-02-13 04:30 UTC, syg0629 commented on programmers/lv.0/240208-삼각형의완성조건(2).ts
>    }
네 ㅠㅠ 찾았고 수정하였습니다!

2024-02-13 05:07 UTC, f-lab-jake approved these changes

2024-02-13 05:07 UTC, f-lab-jake commented on programmers/lv.0/240208-삼각형의완성조건(2).ts
> +  return Math.min(...sides) * 2 - 1;
잘했습니다. for문을 돌면서 하나하나 세고있는거에서 이상한걸 눈치챘어합니다.

2024-02-13 05:50 UTC, merged