새로푼 문제 2개
syg0629/algorithm pull request #5
Opened 2023-10-12 14:04 UTC by syg0629

2023.10.12
@f-lab-jake 멘토님
새로푼 문제 2개 PR올립니다 !

2023-10-12 15:49 UTC, f-lab-jake requested changes

2023-10-12 15:49 UTC, f-lab-jake commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  let dupCheck: string[] = [];
const를 씁시다. 타입이 배열일때 언제 const를 써야하고 언제 let을 써야하는지 구분할수 있나요?

2023-10-12 15:49 UTC, f-lab-jake commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  }
시간 복잡도가 얼마인가요?

2023-10-12 15:49 UTC, f-lab-jake commented on programmers/lv.1/231011-푸드파이트대회.ts
> +  let leftFood: string = "";
타입을 `number[]`로 바꾸고 다시 풀어봅시다. 그렇게 하면 뭐가 더 좋나요?

2023-10-13 04:32 UTC, syg0629 commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  let dupCheck: string[] = [];
배열 내에서도 변수 자체가 재할당이 되었는지 안되었는지로 구분 가능합니다. push를 써서 값이 추가되니까 let으로만 생각하고 있었네요.. 감사합니다.

2023-10-13 05:15 UTC, syg0629 commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  }
for문 안에 includes()가 있으면 이중 for문으로 시간복잡도는 O(n^2)입니다.

2023-10-13 09:19 UTC, f-lab-jake requested changes

2023-10-13 09:19 UTC, f-lab-jake commented on programmers/lv.1/231013-콜라문제.ts
> +}
중복을 줄여보세요

2023-10-14 14:20 UTC, syg0629 commented on programmers/lv.1/231013-콜라문제.ts
> +}
넵 다시 수정하였습니다!

2023-10-14 14:33 UTC, syg0629 commented on programmers/lv.1/231011-푸드파이트대회.ts
> +  let leftFood: string = "";
`number[]` 타입으로 바꾸고 `join()`메서드를 쓰게되면 문자열 연산할 때의 불필요한 문자열 재생성 및 문자열 참조 변경이 없어서 더 좋습니다!

2023-10-14 15:17 UTC, f-lab-jake requested changes

2023-10-14 15:17 UTC, f-lab-jake commented on programmers/lv.1/231011-푸드파이트대회.ts
> +    placedFood.push(...Array(checkedFood).fill(i));
lodash에서 알맞은 함수를 찾아서 써봅시다

2023-10-14 15:17 UTC, f-lab-jake commented on programmers/lv.1/231011-푸드파이트대회.ts
> +  return placedFood.join("") + 0 + placedFood.reverse().join("");
타입에러가 안뜨네요 의외로. "0"으로 써주는게 낫습니다.

2023-10-14 15:18 UTC, f-lab-jake commented on programmers/lv.1/231011-푸드파이트대회.ts
> +    const checkedFood = Math.floor(food[i] / 2);
이상하지 않나요? 왜 `i`만 저렇게 꺼낸다음에 `food[i]`로 쓰나요?

2023-10-15 04:30 UTC, f-lab-jake commented on programmers/lv.1/231011-푸드파이트대회.ts
> +  let leftFood: string = "";
여기서 좀더 일반화된 배움을 얻을수 있을까요?

2023-10-15 04:31 UTC, f-lab-jake commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  }
O(n)만에 가능하니 고쳐봅시다.

2023-10-15 12:48 UTC, syg0629 commented on programmers/lv.1/231011-푸드파이트대회.ts
> +  let leftFood: string = "";
입력되는 문자열이 길어진다면 string타입 연산보다 number[]의 join메서드가 메모리를 더 효율적으로 쓸 수 있으며 처리 시간면에서도 성능이 좋습니다.

2023-10-15 12:51 UTC, syg0629 commented on programmers/lv.1/231011-푸드파이트대회.ts
> +    const checkedFood = Math.floor(food[i] / 2);
넵 수정하였습니다.

2023-10-15 12:51 UTC, syg0629 commented on programmers/lv.1/231011-푸드파이트대회.ts
> +    placedFood.push(...Array(checkedFood).fill(i));
넵! 찾아서 수정하였습니다.

2023-10-15 16:16 UTC, f-lab-jake requested changes

2023-10-15 16:16 UTC, f-lab-jake commented on programmers/lv.1/231011-푸드파이트대회.ts
> +    placedFood.push(..._.times(checkedFood, () => index));
찾아보니 `repeat`이 아쉽게도 문자열만 되네요. `_.times(checkedFood, _.constant(index))`도 가능합니다

2023-10-15 16:18 UTC, f-lab-jake commented on programmers/lv.1/231011-푸드파이트대회.ts
> +  let leftFood: string = "";
일단, 메모리를 더 효율적으로 쓸수있는게 정말 맞나요? 정확히 근거를 대봅시다. 처리시간도 마찬가지입니다.

성능과 관련된 장/단 비교는 너무 쉽습니다. 제가 생각해보라고하는 장단점은 코드의 의미와 관련된것입니다.
바꾼 코드가 어떤면에서 더 나은 의미를 갖고있나요?

그리고 일반화된 배움이란건, 딱 이 문제의 특수한 경우가 아닌 다른 문제나 프로그래밍 전반에 걸쳐 적용할수있는 배움을 말합니다.
말씀하신건 그런 내용이 아니죠.

2023-10-15 16:18 UTC, f-lab-jake approved these changes

2023-10-16 12:02 UTC, syg0629 commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  }
넵 수정하였습니다. 기존 작성했던 코드는 for문 안에 includes(), lastIndexOf()로 배열을 순회하면서 해당되는 원소를 찾아 시간복잡도가 증가하나 객체를 사용해서 객체의 프로퍼티를 바로 찾으니 O(n)이 되네요!

2023-10-16 12:03 UTC, syg0629 commented on programmers/lv.1/231011-푸드파이트대회.ts
> +    placedFood.push(..._.times(checkedFood, () => index));
오 말씀해주신걸로도 반영해보았습니다 :)!

2023-10-16 13:09 UTC, f-lab-jake requested changes

2023-10-16 13:09 UTC, f-lab-jake commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  for (const [index, value] of Object.entries(s)) {
`s.entries()`로 하면 `index`가 `number`타입으로 옵니다.

2023-10-16 13:09 UTC, f-lab-jake commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  const distanceChk: Record<string, number> = {};
`Map`을 써볼까요?
그리고 `distanceChk`는 좋지못한 변수명입니다. 저는 `lastIndices` 정도가 떠오르는데요. 
두 변수명이 어떤 차이가 있을까요? 접근 자체가 다릅니다.

2023-10-16 13:09 UTC, f-lab-jake commented on programmers/lv.1/231011-푸드파이트대회.ts
> +    placedFood.push(..._.times(checkedFood, _.constant(index)));
이건 꼭 이렇게 바꾸란건 아니었습니다ㅋㅋ
그냥 저런 방식도 있다 정도입니다.

2023-10-16 13:39 UTC, f-lab-jake commented on programmers/lv.1/231011-푸드파이트대회.ts
> +    placedFood.push(..._.times(checkedFood, () => index));
아 저런 방법도 있다 정도였습니다. 매번 저런 스타일을 따르려고 할 필욘없습니다.

2023-10-17 15:11 UTC, syg0629 commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  for (const [index, value] of Object.entries(s)) {
처음에 그렇게 했었는데 `s`가 `string`이여서 `property 'entries' does not exist on type 'string'.ts(2339)` 타입스크립트 오류가 뜨길래 `Object.entries(s)`를 찾아보게 되었습니다.  `s.split("")`을 해서 변수를 선언하고 `변수.entries()`를 사용하면 되는 것 덕분에 확인했습니다 :)

2023-10-18 02:37 UTC, f-lab-jake requested changes

2023-10-18 02:37 UTC, f-lab-jake commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  s.split("").map((x: string, i: number) => {
리턴 없는 `map`을 쓰지마세요. `s.entries()`쓰시면 됩니다

2023-10-18 09:31 UTC, merged

2023-10-19 05:51 UTC, syg0629 commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +  s.split("").map((x: string, i: number) => {
넵 수정하였습니다~