새로푼 문제(23.10.18)
syg0629/algorithm pull request #6
Opened 2023-10-18 09:35 UTC by syg0629

2023.10.18
@f-lab-jake 멘토님~
새로푼 문제 4개 PR올립니다.

2023-10-18 15:09 UTC, f-lab-jake requested changes

2023-10-18 15:09 UTC, f-lab-jake commented on programmers/lv.2/231018-H-Index.ts
> +  return undefined ?? citations.length;
`undefined ??` 는 무슨의도인가요? 나머지는 잘했습니다

2023-10-18 15:09 UTC, f-lab-jake commented on programmers/lv.2/231018-멀리뛰기.ts
> +    fNum.push((fNum[i] = (fNum[i - 1] + fNum[i - 2]) % 1234567));
같은 의미를가지는 로직이 두개가있습니다

2023-10-19 05:28 UTC, syg0629 commented on programmers/lv.2/231018-H-Index.ts
> +  return undefined ?? citations.length;
`console.log(solution([3, 4]));`면 값이 `2`가 나와야하는데 `undefinded`가 나옵니다.
`undefinded`면 마지막 paperNum을 출력하고 싶어서 `undefined ?? citations.length`를 넣게 되었습니다.

2023-10-19 05:52 UTC, syg0629 commented on programmers/lv.2/231018-멀리뛰기.ts
> +    fNum.push((fNum[i] = (fNum[i - 1] + fNum[i - 2]) % 1234567));
배열 인덱스로 요소를 추가할 수 있군요 ㅠㅠ 넵 수정하였습니다!

2023-10-20 14:22 UTC, merged

2023-10-20 14:30 UTC, f-lab-jake commented on programmers/lv.2/231018-H-Index.ts
> +  return undefined ?? citations.length;
?? 동작에 대해 알아봅시다. 그리고 어디쓰라고 만들어진 연산자인지도 생각해봅시다.

2023-10-21 08:06 UTC, syg0629 commented on programmers/lv.2/231018-H-Index.ts
> +  return undefined ?? citations.length;
왼쪽 피연산자가 null 또는 undefined일 때 오른쪽 피연산자를 반환하고 그렇지 않으면 왼쪽 피연산자를 반환합니다. return citations.length;이라고만 작성해도 됐네요...

2023-10-23 07:35 UTC, syg0629 commented on programmers/lv.2/231018-H-Index.ts
> +  return undefined ?? citations.length;
데이터를 받아서 사용할 때 데이터가 늦게 도착하는 경우 변수가 일시적으로 undefined가 뜰 수 있는데 이부분을 방지하기 위해 ?? 연산자를 사용합니다.

2023-10-23 08:26 UTC, f-lab-jake commented on programmers/lv.2/231018-피보나치수.ts
>    for (let i = 3; i <= n; i++) {
`i=2`로 해도되고 그게 더 낫습니다. 왜그럴까요?

2023-10-23 09:01 UTC, syg0629 commented on programmers/lv.2/231018-피보나치수.ts
>    for (let i = 3; i <= n; i++) {
`i=2`로 하더라도 `fNum[i] = (fNum[i - 1] + fNum[i - 2]) % 1234567;`으로 계산이 되어지고 문제에서 주어진 내용도 `피보나치 수는 F(0) = 0, F(1) = 1일 때` 이기 때문입니다.

2023-10-23 14:29 UTC, syg0629 commented on programmers/lv.2/231018-피보나치수.ts
>    for (let i = 3; i <= n; i++) {
`i = 3`을 하게 되면 `fNum` 변수 값은 `[0, 1, 1]`으로 대입, `i = 2`로 하게 되면 `[0, 1]`으로 대입하게 됩니다.
변수에 값을 대입 해주는게 다음 코드인 `fNum[i] = (fNum[i - 1] + fNum[i - 2]) % 1234567;`으로 값이 나오지 않으니 대입을 시키는 거라 볼 수 있어 `i = 3`을 하게되면 올바른 결과가 나오지 않아 `fNum` 변수 값에 추가로 `1`도 추가되었다고 생각할 수 있어 `i = 2`가 더 나은 코드 같습니다.