새로푼 문제 2개
syg0629/algorithm pull request #7
Opened 2023-10-21 07:15 UTC by syg0629

2023.10.21
@f-lab-jake 멘토님
새로푼 문제 2개 PR올립니다.

2023-10-23 05:50 UTC, f-lab-jake requested changes

2023-10-23 05:50 UTC, f-lab-jake commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +      answer.push(index - lastIndices.get(value)!);
중복을 줄여봅시다

2023-10-23 07:50 UTC, syg0629 commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +      answer.push(index - lastIndices.get(value)!);
넵 수정하였습니다.

2023-10-23 08:27 UTC, f-lab-jake requested changes

2023-10-23 08:27 UTC, f-lab-jake commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +      answer.push(index - lastIndex!);
여기서 `!`를 안써도 타입체크를 통과할텐데요. 왜그럴까요?

2023-10-23 09:03 UTC, f-lab-jake commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +      answer.push(index - lastIndex!);
그렇다면 처음 코드에서는 왜 !가 필요했을까요? 왜 TS 타입체커가 지금처럼 똑똑하게 처리하지 못할까요?

2023-10-23 09:23 UTC, syg0629 commented on programmers/lv.1/231010-가장가까운같은글자.ts
> +      answer.push(index - lastIndex!);
`lastIndices.get(value)`에 어떤 값이 들어가는지 지정해주지 않아 TS타입체커가 생각하기엔 undefined가 나올 수 있기에 `!`가 필요했습니다.

2023-10-25 04:43 UTC, syg0629 commented on programmers/lv.2/231020-숫자의표현.ts
> +}
주어진 숫자인 n의 약수를 구하고 약수 중에서도 홀수의 개수를 구하면 연속한 자연수의 값과 같습니다.

2023-10-25 04:45 UTC, syg0629 commented on programmers/lv.2/231020-숫자의표현.ts
> +}
너무 한번에 구하려고 했는데 if문을 두개로 나누어 놓을까요...?

2023-10-25 06:19 UTC, syg0629 commented on programmers/lv.1/231020-K번째수.ts
> +  for (let i = 0; i < commands.length; i++) {
인덱스를 안쓰고 구조 분해 할당으로 가능하군요...
단순 조회, `sort`, `slice` 메서드 등을 쓸 수 있는 곳에는 인덱스를 안써도 되고, 
인덱스로 직접적으로 값을 바꾸는 경우에는 써야할 것 같네요.. 
넵 고민해보겠습니다.

2023-10-25 06:22 UTC, f-lab-jake requested changes

2023-10-25 06:22 UTC, f-lab-jake commented on programmers/lv.1/231020-K번째수.ts
>  function solution(array: number[], commands: number[][]): number[] {
`commands: [number, number, number][]`로 하는게 낫습니다.

2023-10-25 13:31 UTC, f-lab-jake requested changes

2023-10-25 13:31 UTC, f-lab-jake commented on programmers/lv.1/231020-K번째수.ts
>      const [cutStart, cutEnd, index]: number[] = x;
제 피드백을 고민없으 그냥 적용하면 안됩니다.
일단 저 번경의 의미를 이해했다면 여기 타입도 바뀌어야겠죠?

그리고 이 변경이 왜 좋은지도 생각해야할겁니다.

2023-10-26 03:24 UTC, syg0629 commented on programmers/lv.1/231020-K번째수.ts
>      const [cutStart, cutEnd, index]: number[] = x;
`number[][]` -> `[number, number, number][]` 변경의 좋은 점은 어떤 데이터가 들어가는지 명확하게 알 수 있다는 점과 유지보수를 하게 될 때 다른 사람이봐도 그 규칙을 빨리 파악할 수 있다는 점입니다.

2023-10-26 03:27 UTC, merged

2023-10-26 06:37 UTC, f-lab-jake commented on programmers/lv.1/231020-K번째수.ts
>      const [cutStart, cutEnd, index]: number[] = x;
명확해진다 <- 같은게 스스로를 속이기 쉬운 설명입니다. 명확하면 당연히 좋잖아요?
왜 명확한가요? 

또 바뀐 코드가 변경에 대해 안전한 구체적인 시나리오를 제시해봅시다

2023-10-26 22:53 UTC, syg0629 commented on programmers/lv.1/231020-K번째수.ts
>  function solution(array: number[], commands: number[][]): number[] {
넵 알겠습니다~

2023-10-26 23:14 UTC, syg0629 commented on programmers/lv.1/231020-K번째수.ts
>      const [cutStart, cutEnd, index]: number[] = x;
`number[][]`로 되어있을 땐 들어가는 배열의 타입은 알아도 배열의 길이가 어떻게 되는지는 코드를 봐야 아는 부분인데, `[number, number, number][]`으로 명시적으로 써주게 되면 그에 맞는 코드를 작성할 수 있습니다.

2023-10-27 00:48 UTC, f-lab-jake commented on programmers/lv.1/231020-K번째수.ts
>      const [cutStart, cutEnd, index]: number[] = x;
네 맞습니다. 그런데 ' 변경에 대해 안전한 구체적인 시나리오'를 제시한건 아니지요.
가령 원래 `number[]`로 했을때 
`const [cutStart, cutEnd, index, x]: number[] = x;` 이렇게 `x`라는 실제론 없는 값을 추가로 destructuring을 했을때 타입체커가 잡아주지 못합니다. `[number, number, number][]`는 아니죠.
그리고 `[start: number, end: number, index: number][]` 처럼 이름을 지어주는게 낫습니다.