새로푼 문제 1개 및 23.10.24에 올렸던 새로푼 문제 3개
syg0629/algorithm pull request #9
Opened 2023-10-26 06:01 UTC by syg0629

2023.10.26
@f-lab-jake 멘토님
새로푼 문제 1개 및 23.10.24에 올렸던 새로푼 문제 3개 PR올립니다.

2023-10-26 06:43 UTC, f-lab-jake requested changes

2023-10-26 06:43 UTC, f-lab-jake commented on programmers/lv.2/231026-구명보트.ts
> +    let heavy: number | undefined = people.pop();
`while(true)`로 해놓고 고쳐봅시다

2023-10-26 06:43 UTC, f-lab-jake commented on programmers/lv.2/231024-괄호회전하기.ts
> +    }
이 로직을 함수로 분리해봅시다.

2023-10-26 06:43 UTC, f-lab-jake commented on programmers/lv.2/231024-괄호회전하기.ts
> +  for (const [index] of s.split("").entries()) {
같은 실수를 반복하지 맙시다

2023-10-26 06:43 UTC, f-lab-jake commented on programmers/lv.2/231023-영어끝말잇기.ts
> +    if (words[i - 1].slice(-1) !== words[i].slice(0, 1)) {
`slice`를 쓰지 말아봅시다.

2023-10-26 06:43 UTC, f-lab-jake commented on programmers/lv.2/231023-영어끝말잇기.ts
> +    const turn: number = Math.floor(i / n) + 1;
`Math.floor`를 쓰지 말아봅시다

2023-10-26 22:52 UTC, syg0629 commented on programmers/lv.2/231023-영어끝말잇기.ts
> +    if (words[i - 1].slice(-1) !== words[i].slice(0, 1)) {
`substring` 으로 수정하였습니다.

2023-10-26 22:52 UTC, syg0629 commented on programmers/lv.2/231023-영어끝말잇기.ts
> +    const turn: number = Math.floor(i / n) + 1;
`Math.trunc` 으로 수정하였습니다.

2023-10-26 22:52 UTC, syg0629 commented on programmers/lv.2/231026-구명보트.ts
> +    let heavy: number | undefined = people.pop();
넵 수정하였습니다.

2023-10-27 00:45 UTC, f-lab-jake requested changes

2023-10-27 00:45 UTC, f-lab-jake commented on programmers/lv.2/231023-영어끝말잇기.ts
> +      words[i].substring(0, 1)
왜 `substring`을 썼나요?

2023-10-27 00:45 UTC, f-lab-jake commented on programmers/lv.2/231026-구명보트.ts
> +    }
이걸 없애고 위의 `people.pop()`의 결과값을 이용해서 break해보세요.

2023-10-28 02:58 UTC, syg0629 commented on programmers/lv.2/231023-영어끝말잇기.ts
> +      words[i].substring(0, 1)
`slice`와 비슷한 역할을 해서 그런지 다른 방법으로 문자열을 잘라주는 메서드를 생각하다보니 사용하게 되었습니다.

2023-10-28 02:58 UTC, syg0629 commented on programmers/lv.2/231026-구명보트.ts
> +    }
넵 수정하였습니다 :)

2023-10-28 02:59 UTC, syg0629 commented on programmers/lv.2/231024-괄호회전하기.ts
> +  for (const [index] of s.split("").entries()) {
넵! 알려주셔서 감사합니다 🤗

2023-10-28 02:59 UTC, syg0629 commented on programmers/lv.2/231024-괄호회전하기.ts
> +    }
넵 분리하였습니다.

2023-10-28 07:52 UTC, f-lab-jake requested changes

2023-10-28 07:52 UTC, f-lab-jake commented on programmers/lv.2/231024-괄호회전하기.ts
> +function validCorBracket(rotated: string): number {
분리한 함수에서 불필요한 부분을 찾고 정리해보세요.

2023-10-28 10:51 UTC, syg0629 commented on programmers/lv.2/231024-괄호회전하기.ts
> +function validCorBracket(rotated: string): number {
넵 정리하였습니다!!

2023-10-29 04:20 UTC, f-lab-jake requested changes

2023-10-29 04:20 UTC, f-lab-jake commented on programmers/lv.2/231024-괄호회전하기.ts
> +function validCorBracket(rotated: string): boolean {
더 간결하게 할수있습니다.

2023-10-29 04:20 UTC, f-lab-jake commented on programmers/lv.2/231024-괄호회전하기.ts
> +function validCorBracket(rotated: string): boolean {
타입은 맞았습니다

2023-10-29 06:19 UTC, syg0629 commented on programmers/lv.2/231024-괄호회전하기.ts
> +function validCorBracket(rotated: string): boolean {
넵! 더 간결하게 만들었습니다~

2023-10-29 08:51 UTC, f-lab-jake approved these changes
잘 찾았습니다.
애초에 함수를 분리하라고 한 주된 이유가 이것때문이었습니다.
분리해놓으면 각각의 코드를 더 쉽게 짤수있게됩니다.

2023-10-29 09:33 UTC, merged